---
- hosts: all
  become: true
  tasks:
  - name: Enable Huge Pages
    lineinfile:
      path: /etc/sysctl.conf
      line: vm.nr_hugepages = 512
      create: yes

  - name: Update sysctl values
    command: sysctl -q -p
  
  - name: Configure node ip
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
      create: yes

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: Copy the join command to server location
    copy: src=join-command dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh
